version: '3.8'

services:
  # O Backend da aplicação construído no NestJS
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: dattebayo_api
    restart: unless-stopped
    ports:
      # Expõe a porta 3000 do Nest para o hospedeiro local
      - "3000:3000"
    environment:
      - NODE_ENV=development
      # O banco de dados do Prisma agora usará o PostgreSQL
      - DATABASE_URL=postgresql://dattebayo:dattebayo_password@db:5432/dattebayo_db?schema=public
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:15-alpine
    container_name: dattebayo_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: dattebayo
      POSTGRES_PASSWORD: dattebayo_password
      POSTGRES_DB: dattebayo_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

  # Front-end da Aplicação Web em Next.js
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    container_name: dattebayo_web
    restart: unless-stopped
    ports:
      # Expõe a porta 80 para acesso no navegador
      - "80:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - api
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  pgdata:
